require 'aws-sdk'
require 'cloudfinder-ec2/version'
require 'cloudfinder-ec2/consts'
require 'cloudfinder-ec2/instance'
require 'cloudfinder-ec2/cluster'
require 'cloudfinder-ec2/clusterfinder'
require 'cloudfinder-ec2/detector'
require 'cloudfinder-ec2/command/list'